puts "The students of Villains Academy"
puts "------------------"
puts "Darth Vader"
puts "Fire Lord Ozai"
puts "The Joker"
puts "All For One"
puts "Ganon"
puts "M. Bison"
puts "Psycho Mantis"
puts "Joffrey Baratheon"
puts "Blackbeard"
puts "Thanos"
puts "Gary"
